// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcgen

type EmbeddingCache struct {
	CacheKey  string
	Embedding []byte
}

type Product struct {
	ID          int64
	ProductID   string
	ProductName string
	Category    string
	Description string
	Rating      float64
}
