// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sqlite_queries.sql

package sqlcgen

import (
	"context"
)

const getEmbeddingCache = `-- name: GetEmbeddingCache :one
SELECT embedding FROM embedding_cache WHERE cache_key = ?
`

func (q *Queries) GetEmbeddingCache(ctx context.Context, cacheKey string) ([]byte, error) {
	row := q.db.QueryRowContext(ctx, getEmbeddingCache, cacheKey)
	var embedding []byte
	err := row.Scan(&embedding)
	return embedding, err
}

const getProductByProductID = `-- name: GetProductByProductID :one
SELECT id, product_id, product_name, category, description, rating
FROM products WHERE product_id = ?
`

func (q *Queries) GetProductByProductID(ctx context.Context, productID string) (Product, error) {
	row := q.db.QueryRowContext(ctx, getProductByProductID, productID)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.ProductName,
		&i.Category,
		&i.Description,
		&i.Rating,
	)
	return i, err
}

const upsertEmbeddingCache = `-- name: UpsertEmbeddingCache :exec
INSERT OR REPLACE INTO embedding_cache (cache_key, embedding) VALUES (?, ?)
`

type UpsertEmbeddingCacheParams struct {
	CacheKey  string
	Embedding []byte
}

func (q *Queries) UpsertEmbeddingCache(ctx context.Context, arg UpsertEmbeddingCacheParams) error {
	_, err := q.db.ExecContext(ctx, upsertEmbeddingCache, arg.CacheKey, arg.Embedding)
	return err
}

const upsertProduct = `-- name: UpsertProduct :one
INSERT INTO products (product_id, product_name, category, description, rating)
VALUES (?, ?, ?, ?, ?)
ON CONFLICT(product_id) DO UPDATE SET
    product_name = excluded.product_name,
    category     = excluded.category,
    description  = excluded.description,
    rating       = excluded.rating
RETURNING id
`

type UpsertProductParams struct {
	ProductID   string
	ProductName string
	Category    string
	Description string
	Rating      float64
}

func (q *Queries) UpsertProduct(ctx context.Context, arg UpsertProductParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, upsertProduct,
		arg.ProductID,
		arg.ProductName,
		arg.Category,
		arg.Description,
		arg.Rating,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}
